---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nextgold/api-studio.nextgoldtech.com
    - /bin/cp .env.production $DEPLOYPATH/.env
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH
    - /usr/local/bin/php /usr/local/bin/composer install --no-dev
    - /usr/local/bin/php artisan migrate --force
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan route:cache
    - /usr/local/bin/php artisan view:cache
